### ISSUE TITLE
Add All Virtualization Modules

### ISSUE THREAD

**Issue by FragmentedPacket** [FragmentedPacket/netbox_modules#16]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

- cluster-types
- cluster-groups
- clusters
- virtual-machines
- interfaces

I believe there is a PR for a few of these, I will move them from Ansible PR into modules here and credit the author of the modules and then create the remaining

**Comment by MrRussLuther** [comment]
Hey, I'm a college intern and my naivety might be showing here, but I was thinking that if I were to use the ansible module "netbox_device.py" as a template couldn't I just change the "app" and "endpoint" variables over to "virtualization", and "virtual_machines", update the module_utils dictionary to include the new endpoint and start calling this new module?

We're currently trying to switch over to using Netbox as a Source of Truth and we mainly use ansible to provision hosts. So far your devices module is flawless, but we store a lot of our hosts as "Virtual Machines" so this is a pretty necessary feature.
Would love to make this feature a PR and merge it in, but want to make sure I'm on the right track before working on this.

**Comment by FragmentedPacket** [comment]
You're correct. Adding new modules for the most part should be straight forward and be able to use other modules as a reference.

There is also an updated README that goes over contributing and what things need to be updated.

If you'd like there are two PRs open within Ansible to add the virtual machines and clusters:
https://github.com/ansible/ansible/pull/62054
https://github.com/ansible/ansible/pull/62058

If you want to just implement the virtual_machines that is fine and just add yourself in as an author along with the person that created that within Ansible.

I can also help with adding tests, etc. if need be
